os: linux
version: ~> 1.0
language: php
dist: jammy

php:
  - 8.0

matrix:
  fast_finish: true
before_install:
  # Disable xdebug.
  - nvm install v20.16.0
  - nvm use v20.16.0
install:
  - npm install
cache:
  directories:
    - '$HOME/.npm'
before_script:
  - php --version
  - node --version
  - npm --version

script: true
deploy:
  - provider: releases
    file_glob: true
    edge: true
    token: $GITHUB_TOKEN
    overwrite: true
    skip_cleanup: true
    draft: true
    'on':
      repo: manishnagdewani-dev/test_dpl
      branch: main
