# os: linux
# version: ~> 1.0
# language: php
# arch: arm64-graviton2
# virt: vm
# dist: focal

dist: focal

services:
  - docker

language: scala

scala:
  - 2.13.6

before_script: rvm use ruby-3.1.2
   
script: true
deploy:
  - provider: releases
    file_glob: true
    token: $GITHUB_TOKEN
    overwrite: true
    skip_cleanup: true
    draft: true
    'on':
      repo: manishnagdewani-dev/test_dpl
      branch: main
