os: linux
version: ~> 1.0
language: php
dist: jammy

php:
  - 8.0

matrix:
  fast_finish: true

before_script:
  - php --version
  - node --version
  - npm --version

script: true
deploy:
  - provider: releases
    file_glob: true
    edge:
      branch: v2.0.2.beta.1
    token: $GITHUB_TOKEN
    overwrite: true
    skip_cleanup: true
    draft: true
    'on':
      repo: manishnagdewani-dev/test_dpl
      branch: main
