language: php
services:
- docker
php:
- '7.2'
script: true
deploy:
  - provider: releases
    file_glob: true
    token: $GITHUB_TOKEN
    overwrite: true
    skip_cleanup: true
    draft: true
    'on':
      repo: manishnagdewani-dev/test_dpl
      branch: main
