os: linux
version: ~> 1.0
language: c
arch: arm64-graviton2
virt: vm
dist: focal
group: edge

script: uname -a
deploy:
  - provider: releases
    file_glob: true
    token: $GITHUB_TOKEN
    overwrite: true
    skip_cleanup: true
    draft: true
    'on':
      repo: manishnagdewani-dev/test_dpl
      branch: main
