# os: linux
# version: ~> 1.0
# language: php
# arch: arm64-graviton2
# virt: vm
# dist: focal

dist: focal

services:
  - docker

language: scala

scala:
  - 2.13.6

# before_deploy:
#   - rvm use ruby-3.1.2 --default
#   - gem install uri -v '1.0.1'
   
script: true
deploy:
  - provider: releases
    file_glob: true
    dpl_version: 2.0.3.beta.4
    token: $GITHUB_TOKEN
    overwrite: true
    skip_cleanup: true
    draft: true
    'on':
      repo: manishnagdewani-dev/test_dpl
      branch: main
